import type { Tour } from "../tour.js";

export const tour: Tour = {
  id: "christopher-wren-tour",
  guideId: "christopher-wren",
  guideName: "Christopher Wren",
  title: "Wren's Phoenix: Rebuilding the Sacred City",
  summary: "Walk the streets Christopher Wren rebuilt after the Great Fire, from the Monument's ashes to St Paul's soaring dome—a masterpiece born from catastrophe.",
  durationMin: 75,
  distanceM: 2100,
  voiceHint: "measured, visionary older Englishman, precise and proud",
  stops: [
    {
      id: "monument-fire",
      name: "The Monument to the Great Fire",
      lat: 51.5105,
      lng: -0.0754,
      kind: "historic",
      blurb: "Where London burned, and Wren's task began",
      narration: "I stand here still, where six million pounds of timber and thatch became ash in five days. September 1666—I was young then, newly professor at Oxford, when the King summoned me to survey the ruin. This column marks the fire's origin, and my own commission. Every church, every street you shall see today rose from my hand, my theodolite, my conviction that London need not merely rebuild—it must be reborn.",
      walkToNext: "280m northwest to St Paul's Cathedral via Cannon Street",
      partner: undefined,
    },
    {
      id: "st-pauls",
      name: "St Paul's Cathedral",
      lat: 51.5153,
      lng: -0.0983,
      kind: "historic",
      blurb: "The dome that reshaped an entire city's skyline",
      narration: "Thirty-five years I gave to this! The old cathedral was a blackened shell, yet my vision would not be confined by what came before. That dome, you see it? Mathematical perfection married to divine geometry. I sketched it first in my study, staked my reputation upon it. When they laid the final stone in 1710, I wept. This is not merely a church; it is London's declaration that we shall endure, that beauty rises from ruin.",
      walkToNext: "200m south to Bean There Coffee House via Cheapside",
      partner: undefined,
    },
    {
      id: "bean-there",
      name: "Bean There Coffee House",
      lat: 51.5141,
      lng: -0.0961,
      kind: "partner",
      blurb: "Pause for coffee in the shadow of the great cathedral",
      narration: "I myself favored coffee houses—places where architects and merchants spoke freely of the city's future. This corner has served such purposes for centuries. Within these walls, over a cup of strong black coffee and warm bread, one reflects on the enormity of what must be rebuilt. The weight of empire, the mathematics of stone. Do sit; the owner extends a courtesy of twenty percent to visitors of this walk.",
      walkToNext: "180m southeast to St Mary-le-Bow via Bow Lane",
      partner: {
        venue: "Bean There Coffee House",
        offer: "20% discount on coffee and pastries for walking tour guests",
      },
    },
    {
      id: "mary-le-bow",
      name: "St Mary-le-Bow",
      lat: 51.5133,
      lng: -0.0939,
      kind: "historic",
      blurb: "The church whose bells defined the City proper",
      narration: "A Londoner born within earshot of Bow's bells—that was the ancient saying. My design here was deliberate: elegant, economical, yet unmistakably mine. Notice the steeple's tiers, the ascending geometry that catches light as the sun moves. Fifty churches I rebuilt or designed after the Fire. This one, with its tower rising 68 metres, became one of London's beloved landmarks. I refused to merely replace what was lost; I elevated it.",
      walkToNext: "240m south to St Stephen Walbrook via Walbrook Street",
      partner: undefined,
    },
    {
      id: "st-stephen",
      name: "St Stephen Walbrook",
      lat: 51.5104,
      lng: -0.0888,
      kind: "historic",
      blurb: "The jewel of Wren's smaller designs, a perfect geometrical gem",
      narration: "Some call this my most complete church. Not the grandest, but perhaps the most perfectly formed. I spent the same care here as upon the Cathedral itself—every proportion, every arch in service of proportion and light. The central dome, the rectangular nave beneath—see how the eye moves upward? This is not accident. Forty-two years I served as Surveyor, and in designs like this I showed that even in modest parishes, the language of beauty remains mathematically pure and spiritually true.",
      walkToNext: "220m southwest to St Margaret Lothbury via King Street",
      partner: undefined,
    },
    {
      id: "the-old-bell",
      name: "The Old Bell Tavern",
      lat: 51.5122,
      lng: -0.0921,
      kind: "partner",
      blurb: "Historic ale house where the City's architects and merchants gathered",
      narration: "This tavern predates even the Fire. I myself supped here during the rebuilding years, surrounded by masons, carpenters, and men of commerce. A place where the city's business is still conducted over ale and good English fare. The proprietor honours this history and welcomes those who walk the Wren route—a pint or simple meal as a token of the old City's resilience. This is where dreams of rebuilding became brick and mortar and human sweat.",
      walkToNext: "240m northwest to Church of St Vedast via Foster Lane",
      partner: {
        venue: "The Old Bell Tavern",
        offer: "Complimentary ale or soft drink with any lunch order for walking tour guests",
      },
    },
    {
      id: "st-vedast",
      name: "Church of St Vedast",
      lat: 51.5128,
      lng: -0.0954,
      kind: "historic",
      blurb: "Final triumph: an intricate spire crowning a lifetime of vision",
      narration: "Eighty-eight years old, and I was still thinking of spires. St Vedast's steeple rose in the last years of my work—slender, ascending in octagonal tiers toward the sky like a prayer made stone. By this time, others had carried much of the burden, yet my hand guided still. The churches were finished; the city reborn. I had given London not merely buildings but a philosophy: that from catastrophe comes the chance to build something eternally beautiful, and that mathematics and faith are one.",
      walkToNext: undefined,
      partner: undefined,
    },
  ],
};
